// <auto-generated />
using System;
using EnozomTask.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnozomTask.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260917144422_UpdateTripStops")]
    partial class UpdateTripStops
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EnozomTask.Domain.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Alexandria"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Damnhour"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tanta"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Banha"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cairo"
                        });
                });

            modelBuilder.Entity("EnozomTask.Domain.Models.Train", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Trains");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Talgo"
                        },
                        new
                        {
                            Id = 2,
                            Name = "French"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Spain"
                        });
                });

            modelBuilder.Entity("EnozomTask.Domain.Models.Trip", b =>
                {
                    b.Property<int>("TripNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TripNumber"));

                    b.Property<int>("TrainId")
                        .HasColumnType("int");

                    b.HasKey("TripNumber");

                    b.HasIndex("TrainId");

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            TripNumber = 1,
                            TrainId = 1
                        },
                        new
                        {
                            TripNumber = 2,
                            TrainId = 2
                        },
                        new
                        {
                            TripNumber = 3,
                            TrainId = 3
                        },
                        new
                        {
                            TripNumber = 4,
                            TrainId = 1
                        },
                        new
                        {
                            TripNumber = 5,
                            TrainId = 2
                        },
                        new
                        {
                            TripNumber = 6,
                            TrainId = 3
                        });
                });

            modelBuilder.Entity("EnozomTask.Domain.Models.TripStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<int>("StopOrder")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time(6)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.HasIndex("TripId");

                    b.ToTable("TripStops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StationId = 1,
                            StopOrder = 1,
                            Time = new TimeSpan(0, 7, 0, 0, 0),
                            TripId = 1
                        },
                        new
                        {
                            Id = 2,
                            StationId = 5,
                            StopOrder = 2,
                            Time = new TimeSpan(0, 9, 0, 0, 0),
                            TripId = 1
                        },
                        new
                        {
                            Id = 3,
                            StationId = 1,
                            StopOrder = 1,
                            Time = new TimeSpan(0, 7, 30, 0, 0),
                            TripId = 2
                        },
                        new
                        {
                            Id = 4,
                            StationId = 3,
                            StopOrder = 2,
                            Time = new TimeSpan(0, 8, 30, 0, 0),
                            TripId = 2
                        },
                        new
                        {
                            Id = 5,
                            StationId = 4,
                            StopOrder = 3,
                            Time = new TimeSpan(0, 9, 30, 0, 0),
                            TripId = 2
                        },
                        new
                        {
                            Id = 6,
                            StationId = 5,
                            StopOrder = 4,
                            Time = new TimeSpan(0, 10, 30, 0, 0),
                            TripId = 2
                        },
                        new
                        {
                            Id = 7,
                            StationId = 1,
                            StopOrder = 1,
                            Time = new TimeSpan(0, 9, 0, 0, 0),
                            TripId = 3
                        },
                        new
                        {
                            Id = 8,
                            StationId = 3,
                            StopOrder = 2,
                            Time = new TimeSpan(0, 10, 15, 0, 0),
                            TripId = 3
                        },
                        new
                        {
                            Id = 9,
                            StationId = 5,
                            StopOrder = 3,
                            Time = new TimeSpan(0, 11, 30, 0, 0),
                            TripId = 3
                        },
                        new
                        {
                            Id = 10,
                            StationId = 5,
                            StopOrder = 1,
                            Time = new TimeSpan(0, 7, 0, 0, 0),
                            TripId = 4
                        },
                        new
                        {
                            Id = 11,
                            StationId = 5,
                            StopOrder = 5,
                            Time = new TimeSpan(0, 9, 0, 0, 0),
                            TripId = 4
                        },
                        new
                        {
                            Id = 12,
                            StationId = 5,
                            StopOrder = 1,
                            Time = new TimeSpan(0, 10, 30, 0, 0),
                            TripId = 5
                        },
                        new
                        {
                            Id = 13,
                            StationId = 4,
                            StopOrder = 2,
                            Time = new TimeSpan(0, 9, 30, 0, 0),
                            TripId = 5
                        },
                        new
                        {
                            Id = 14,
                            StationId = 3,
                            StopOrder = 3,
                            Time = new TimeSpan(0, 8, 30, 0, 0),
                            TripId = 5
                        },
                        new
                        {
                            Id = 15,
                            StationId = 5,
                            StopOrder = 4,
                            Time = new TimeSpan(0, 8, 0, 0, 0),
                            TripId = 5
                        },
                        new
                        {
                            Id = 16,
                            StationId = 1,
                            StopOrder = 5,
                            Time = new TimeSpan(0, 7, 30, 0, 0),
                            TripId = 5
                        },
                        new
                        {
                            Id = 17,
                            StationId = 5,
                            StopOrder = 1,
                            Time = new TimeSpan(0, 11, 30, 0, 0),
                            TripId = 6
                        },
                        new
                        {
                            Id = 18,
                            StationId = 3,
                            StopOrder = 2,
                            Time = new TimeSpan(0, 10, 15, 0, 0),
                            TripId = 6
                        },
                        new
                        {
                            Id = 19,
                            StationId = 5,
                            StopOrder = 3,
                            Time = new TimeSpan(0, 9, 30, 0, 0),
                            TripId = 6
                        },
                        new
                        {
                            Id = 20,
                            StationId = 1,
                            StopOrder = 4,
                            Time = new TimeSpan(0, 9, 0, 0, 0),
                            TripId = 6
                        });
                });

            modelBuilder.Entity("EnozomTask.Domain.Models.Trip", b =>
                {
                    b.HasOne("EnozomTask.Domain.Models.Train", "Train")
                        .WithMany("Trip")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Train");
                });

            modelBuilder.Entity("EnozomTask.Domain.Models.TripStop", b =>
                {
                    b.HasOne("EnozomTask.Domain.Models.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnozomTask.Domain.Models.Trip", "Trip")
                        .WithMany("TripStops")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("EnozomTask.Domain.Models.Train", b =>
                {
                    b.Navigation("Trip");
                });

            modelBuilder.Entity("EnozomTask.Domain.Models.Trip", b =>
                {
                    b.Navigation("TripStops");
                });
#pragma warning restore 612, 618
        }
    }
}
